name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 需要寫入 gh-pages 分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install jupyter-book

      - name: Build the Jupyter Book
        run: |
          jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          publish_branch: gh-pages
          force_orphan: true   # <-- 每次重建乾淨的 gh-pages